### ISSUE TITLE
debian does not support libzip-dev 1.9 yet

### ISSUE THREAD

**Issue by svenn71** [google/mount-zip#12]
Discover that debian sid is still on 1.7

**Comment by fdegros** [comment]
Indeed, [Debian sid features `libzip-dev` 1.7.3](https://packages.debian.org/sid/libzip-dev), which was [released almost 3 years ago in July 2020](https://libzip.org/news/release-1.7.3.html). Maybe that's an issue that should be raised with the Debian distro.

In the meantime, you'll have to [build `libzip` yourself](https://github.com/nih-at/libzip/blob/main/INSTALL.md) if you want to use it with `mount-zip` on Debian.

**Comment by fdegros** [comment]
`mount-zip` 1.0.14 can now be built with older versions of `libzip` that don't feature `zip_file_is_seekable`.
