### ISSUE TITLE
Instructions for installing on Windows

### ISSUE THREAD

**Issue by dvasdekis** [google/mount-zip#13]
Hi @fdegros, love your persistence in building this to a very high level of quality! Thank you, it's extremely useful.

I'm wondering if you have any interest in creating some documentation for Windows users? To my knowledge, it would be the first open-source tool to mount a zip as a drive on Windows.

Thank you!

**Comment by fdegros** [comment]
Thanks Dimitri.

I don't work on Windows at the moment, and I don't know what's involved in porting `mount-zip` to Windows, and if it is difficult to do so. I believe the underlying `libzip` and Boost.Intrusive libraries work on Windows. Most of `mount-zip` itself is system agnostic, but some parts (such as the FUSE interface, and the creation of temp files) are OS-specific. Also, Windows might have different rules for what constitutes a valid file name, and for the detection of file name collisions (eg case sensitivity).
