### ISSUE TITLE
Add support also for older versions of libzip?

### ISSUE THREAD

**Issue by tenzap** [google/mount-zip#20]
For now, to have a package that can build mount-zip 1.0.13 on Debian/Ubuntu (which ship libzip 1.7.3) I reverted multiple commits of your code without being really sure if it is correct.

Would you update your code to add for example conditionals (like preprocessor macros, or whatever suits best) on the version of libzip so as to enable or disable support for some features (like LZMA since 1.8.0 or zip_file_is_seekable since 1.9.1)?

**Comment by fdegros** [comment]
`libzip` 1.7.3 is almost four years old. Since then, a couple of `libzip` bugs and limitations have been fixed in order to support the correct operation of `mount-zip`.

I would recommend upgrading `libzip` in order to benefit from the various bug fixes and feature improvements. There has been several `libzip` releases in the last years. For example, `libzip` 1.9.1 is almost two years old, and it is the "oldest" version of `libzip` that can support the current version of `mount-zip`.

**Comment by fdegros** [comment]
This error is really strange:

```
mount-zip: Cannot create cache file in '/tmp/nn': Operation not supported
```

Does the specified temp directory `/tmp/nn` actually exist? Is it writable? What is its underlying filesystem? Is it mounted in read-write mode?

Can you try to create a fresh temporary filesystem of type `tmpfs`?

```
$ mkdir tmp
$ sudo mount -t tmpfs -o size=3G tmp tmp
$ df -h tmp
Filesystem      Size  Used Avail Use% Mounted on
tmp             3.0G     0  3.0G   0% /home/fdegros/Downloads/tmp
```

And use it:

```
$ mount-zip -o allow_other --cache=tmp --precache android-ndk-r26b-linux.zip mnt
...
mount-zip: Loaded 100%

$ du -sh mnt
2.1G    mnt

$ df -h mnt
Filesystem      Size  Used Avail Use% Mounted on
mount-zip       2.1G  2.1G     0 100% /home/fdegros/Downloads/mnt

$ tree -a mnt | tail -1
526 directories, 7925 files
```

**Comment by fdegros** [comment]
> It could be that overlayfs doesn't support `O_TMPFILE`.

Bingo. I think this is the actual cause of bug #23. I'll reopen it and I'll update its title.

> Maybe you should have a fallback if it is not supported.

I agree. Let's link this work to bug #23.

> Does this mean that the `--precache` option will unzip to the tmp dir?

Yes, in some sense. When used with the `--precache` option, `mount-zip` creates one unnamed temporary cache file in the tmp dir, and stores all the uncompressed data in there. See the [documentation](https://github.com/google/mount-zip#smart-caching).

**Comment by fdegros** [comment]
`mount-zip` 1.0.14 can now be built with older versions of `libzip` that don't feature `zip_file_is_seekable`.
