### ISSUE TITLE
support leading "./" in filenames

### ISSUE THREAD

**Issue by christianscott** [google/mount-zip#29]
Bazel's zipper tool (`@bazel_tools//tools/zip:zipper`) can create archives that contain entries with a leading `./`:

```
$ echo './README.md' > files.txt
$ ./bazel-bin/external/bazel_tools/third_party/ijar/zipper cC archive.zip @files.txt
$ unzip -l archive.zip
Archive:  archive.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    26319  2010-01-01 00:00   ./README.md
---------                     -------
    26319                     1 file
```

These entries are skipped by `mount-zip` because `Path::Normalize` fails: https://github.com/google/mount-zip/blob/main/lib/path.cc#L205-L206

```
$ ./mount-zip /tmp/archive.zip /tmp/mount/
mount-zip: Skipped File [0]: Cannot normalize path './mount-zip.1'
````

It works if I skip these segments instead of failing:

```c++
    if (part == ".")
      continue;

    if (part.empty() || part == "..")
      return false;
```

```
$ ll /tmp/mount/
total 26K
-rw-r--r-- 1 user user 26K Jan  1  2010 README.md
```

**Comment by fdegros** [comment]
Thanks for the report and the pull request.

Yes, relative paths starting with `./` should be correctly handled. I thought they were, or at least I think they have been supported at some point, but I might be wrong.

I'll have a look at it next week.

**Comment by fdegros** [comment]
If you can, please try with the latest sources. Let me know how it is going.

**Comment by christianscott** [comment]
Working beautifully 🎉 thank you for the prompt fix!

**Comment by fdegros** [comment]
Thanks for the confirmation.

Then, I'm going to release a new official version (1.4) with this fix.
