### ISSUE TITLE
feat: introduce option to fail if the archive contains invalid filenames

### ISSUE THREAD

**Issue by christianscott** [google/mount-zip#31]
hi, another request related to #29 👋

while I imagine it's handy for the mount to succeed even if the mounted archive contains invalid filenames, it would have saved me a little bit of time if it failed instead. I am using this tool to mount archives in a server, and it wasn't immediately obvious why the files weren't available even though the mount succeeded.

making this the default behaviour would be a backwards incompatible change so perhaps this should be introduced via a flag? something like `--noinvalid`, `--strict`, or `--strict-filenames`.

**Comment by christianscott** [comment]
And thank you for open sourcing this tool. I've already built one internal tool using it and plan on building another soon :)

**Comment by fdegros** [comment]
My idea is that `mount-zip` should try to serve all the files of the ZIP archive, even if it has to slightly "rename" some of these files (in case of name collision or of "invalid" filename). If I can achieve this goal, then there is no need to add an extra command line option.

**Comment by christianscott** [comment]
Makes sense 👍

**Comment by fdegros** [comment]
Since `mount-zip` 1.4, all the file paths are considered valid.
