### ISSUE TITLE
compile on macos aarch64

### ISSUE THREAD

**Issue by atomotic** [google/mount-zip#5]
I'm not able to compile on macos aarch64 ([macfuse](https://github.com/osxfuse/osxfuse/releases) 4.4.0).
there is something should i try?

[mount-zip-log.txt](https://github.com/google/mount-zip/files/9198044/mount-zip-log.txt)

**Comment by fdegros** [comment]
I pushed some changes that I hope will fix the build issue. But I cannot confirm whether it is actually fixed or not since I don't use macOS.

Please try again with the latest source code and tell me if it works.

**Comment by atomotic** [comment]
still errors [mount-zip-2022-08-02.txt](https://github.com/google/mount-zip/files/9240115/mount-zip-2022-08-02.txt)
thanks for the support

**Comment by fdegros** [comment]
Now, the error is: `reader.cc:153:25: error: use of undeclared identifier 'posix_fallocate'`

According to [Gnulib's manual](https://www.gnu.org/software/gnulib/manual/html_node/posix_005ffallocate.html), `posix_fallocate` is missing on macOS. We might be able to [work around this limitation](https://stackoverflow.com/a/11497568) by using `fcntl(fd, F_PREALLOCATE, ...)` and `ftruncate()`.

**Comment by fdegros** [comment]
Try again with the latest source. I'm modifying the code "blindly", without a way to check if it even builds on macOS.
