### ISSUE TITLE
libfuse dependency

### ISSUE THREAD

**Issue by glentner** [google/mount-zip#6]
I'm trying to build this and for reasons have created a Homebrew (on Linux) formula (shared below). The challenge I'm left with is that it can't find `libfuse` which is because brew installed libfuse v3 (`fuse3.pc`) and I'm guessing you are assuming v2? I just modified the pkg-config file to present as `fuse` instead of `fuse3` but the API has changed and the compile fails.

What do you recommend?

Brew formula for `mount-zip`:
```ruby
class MountZip < Formula
  desc "FUSE filesystem for ZIP archives"
  homepage "https://github.com/google/mount-zip"
  url "https://github.com/google/mount-zip/archive/refs/tags/v1.0.6.tar.gz"
  version "1.0.6"
  sha256 "2882e32175f5dee68ed9243b1e8b66966584af6223795c2169d3b43c39783f3d"
  license "GPL-3.0"

  depends_on "gcc" => :build
  depends_on "pkg-config" => :build

  depends_on "boost" => :build
  depends_on "libzip" => :build
  depends_on "libfuse" => :build
  depends_on "glib"

  fails_with gcc: "5"

  def install
    system "make"
    system "make", "install"
  end

  test do
    system "make", "check"
  end
end
```

**Comment by fdegros** [comment]
`mount-zip` depends on `libfuse` version 2.
`libfuse` version 3 indeed has a different and incompatible API.

**Comment by fdegros** [comment]
[`mount-zip` 1.8](https://github.com/google/mount-zip/releases/tag/v1.8) uses FUSE 3 by default.
