### ISSUE TITLE
Option for turning off caching

### ISSUE THREAD

**Issue by ncadou** [google/mount-zip#7]
Right now it's not possible to use mount-zip on systems with a read-only filesystem.

Also, mount-zip would be quite useful to access the contents of big zip files on systems with a disk slow enough that the extraction cost is prohibitive, but some read patterns prompt mount-zip to write to that disk enough cache data as to nullify both the time and space savings that mount-zip could potentially offer.

My most extreme use case is when remote mounting nested zip files from S3. So there is a first mount for the S3 bucket, then a mount for a zip file there, which besides other stuff contains an encrypted zip file, which contains a third zip. So that's 4 FUSE mount layers: s3fs and mount-zip x 3. On this particular system network access is faster than disk access, but the many layers of caching results in much disk space and time waste.

The ability to turn off caching would help toward making this process more efficient, the alternative being to download and extract everything.

**Comment by fdegros** [comment]
> Right now it's not possible to use mount-zip on systems with a read-only filesystem.

This assertion needs to be nuanced. The input ZIP archive can perfectly reside on a read-only filesystem. I don't know if the mount point itself can be on a read-only filesystem, but my experiments indicate that it cannot:

```
$ mkdir rofs
$ sudo mount -t tmpfs swap rofs
$ mkdir rofs/mnt
$ sudo mount -o remount,ro rofs
$ mount-zip input.zip rofs/mnt
fusermount: user has no write access to mountpoint /home/fdegros/Downloads/rofs/mnt
```

> Also, mount-zip would be quite useful to access the contents of big zip files on systems with a disk slow enough that the extraction cost is prohibitive, but some read patterns prompt mount-zip to write to that disk enough cache data as to nullify both the time and space savings that mount-zip could potentially offer.

What are you trying to achieve, and with which constraints?

There is a fundamental tension between having compressed data and trying to access data in a non-sequential way.

`mount-zip` only caches data if it detects that compressed or encrypted data is accessed in a non-sequential way. And even in such case, it only extracts just enough data to serve the requested blocks. `mount-zip` doesn't need to cache files that are simply stored uncompressed and unencrypted in the ZIP archive.

The cache file is created in the `/tmp` directory. It is assumed that the `/tmp` directory is either on a local filesystem, or a `tmpfs` backed by swap space. Either way, reading and writing the cache file is supposed to be fast, and in any case faster than decompressing a large file from the top over and over again.

If `mount-zip` cannot create the cache file, or if it cannot reserve enough disk space to store the cached data, then it will do without and try its best to serve the requested data, but some non-sequential access patterns might result in poor performance.

> My most extreme use case is when remote mounting nested zip files from S3. So there is a first mount for the S3 bucket, then a mount for a zip file there, which besides other stuff contains an encrypted zip file, which contains a third zip. So that's 4 FUSE mount layers: s3fs and mount-zip x 3. On this particular system network access is faster than disk access, but the many layers of caching results in much disk space and time waste.

Nested ZIPs present some challenges. The central index of a ZIP is located at the end of this file. So, mounting and serving a ZIP essentially requires random access. If a ZIP is itself located in a mounted ZIP, and if it is not simply stored in this outer ZIP, then it will need to be entirely cached.

> The ability to turn off caching would help toward making this process more efficient, the alternative being to download and extract everything.

At the moment, there is no option to disable caching entirely. However, you might be able to experiment by mounting a `tmpfs` filesystem of appropriate size on `/tmp`.

```
$ sudo mount -t tmpfs swap /tmp
```

You can also observe `mount-zip`'s caching mechanism by running it with the `-f` (for foreground) and `--verbose` options:

```
$ mount-zip -f --verbose input.zip mnt                                                                                      
...
mount-zip: Reader 2: Opened File [0]
mount-zip: Reader 3: Opened File [0]
mount-zip: Reserved 6,777,995,272 bytes in cache file at offset 0
mount-zip: Reader 2: Created Cached Reader 3
mount-zip: Reader 3: Jump 6,777,995,264 from 0 to 6,777,995,264 
mount-zip: Caching 6,777,995,272 bytes... 10%
mount-zip: Caching 6,777,995,272 bytes... 20%
...
mount-zip: Caching 6,777,995,272 bytes... 96%
mount-zip: Cached 6,777,995,272 bytes from 0 to 6,777,995,272 in 19,532 ms
mount-zip: Reader 2: Closed
```

**Comment by ncadou** [comment]
> > Right now it's not possible to use mount-zip on systems with a read-only filesystem.
> 
> This assertion needs to be nuanced. The input ZIP archive can perfectly reside on a read-only filesystem. I don't know if the mount point itself can be on a read-only filesystem, but my experiments indicate that it cannot:

That's also what I found. But at least `/tmp` needs to be writable, presumably because of this: https://github.com/google/mount-zip/blob/main/lib/reader.cc#L102-L111

> > Also, mount-zip would be quite useful to access the contents of big zip files on systems with a disk slow enough that the extraction cost is prohibitive, but some read patterns prompt mount-zip to write to that disk enough cache data as to nullify both the time and space savings that mount-zip could potentially offer.
> 
> What are you trying to achieve, and with which constraints?
> 
> [...]
> 
> If `mount-zip` cannot create the cache file, or if it cannot reserve enough disk space to store the cached data, then it will do without and try its best to serve the requested data, but some non-sequential access patterns might result in poor performance.
>
> [...]
> 
> At the moment, there is no option to disable caching entirely. However, you might be able to experiment by mounting a `tmpfs` filesystem of appropriate size on `/tmp`.

From my findings I don't think it can fully do without cache. It seems to give up as soon as creating the cache file fails.

I have tried tmpfs, but the main constraint is size. With 100+ GB ZIP files, this quickly becomes impractical, and in my case, slow and limited local storage can't work either. Hence my asking whether caching could be fully turned off.

Doesn't have to be an option, although that would be nice, but if at least it could not abort when no cache file can be created, that'd work fine.

**Comment by fdegros** [comment]
I added a `--nocache` command line option that disables caching. Check it out.

> But at least `/tmp` needs to be writable

Generally, the cache directory `/tmp` is expected to be writable. But even if `mount-zip` cannot create a file in the cache directory, it shouldn't crash. It will just keep going and serving data as best as it can, but without caching the uncompressed data. Be aware that, in this case, some non-sequential access patterns might result in poor performance, especially if `mount-zip` has to uncompress the same file over and over again.

> From my findings I don't think it can fully do without cache. It seems to give up as soon as creating the cache file fails.

I'm not sure what you mean by "give up". `mount-zip` should be able to work without crashing even without access to a cache. However, in this case, some access patterns might result in poor performance.

> I have tried tmpfs, but the main constraint is size. With 100+ GB ZIP files, this quickly becomes impractical, and in my case, slow and limited local storage can't work either. Hence my asking whether caching could be fully turned off.

Caching can now be turned off with the `--nocache` command line option. However, I'm not sure that turning off the cache will solve your problem. Anyway, you can try.

> Doesn't have to be an option, although that would be nice, but if at least it could not abort when no cache file can be created, that'd work fine.

What do you mean by "abort" in this case? `mount-zip` shouldn't abort or crash if the cache file cannot be created.

If you notice a crash, please open a bug.
